required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gogo/protobuf/protoc-gen-gofast",
  "github.com/gogo/protobuf/protoc-gen-gogo",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
]

[[constraint]]
  branch = "master"
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/gogo/googleapis"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    non-go = false

  [[prune.project]]
    name = "github.com/mwitkow/go-proto-validators"
    non-go = false

  [[prune.project]]
    name = "github.com/golang/protobuf"
    non-go = false

  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false

  [[prune.project]]
    name = "github.com/gogo/googleapis"
    non-go = false
